export interface AreaData {
  slug: string;
  name: string;
  emirate: 'Dubai' | 'Abu Dhabi';
  tagline: string;
  image: string;
  heroImage: string;
  description: string;
  highlights: string[];
  avgPricePerSqft: string;
  rentalYield: string;
  propertyTypes: string[];
  nearbyAreas: string[];
  lat: number;
  lng: number;
  mapZoom: number;
}

export const areas: AreaData[] = [
  {
    slug: 'downtown-dubai',
    name: 'Downtown Dubai',
    emirate: 'Dubai',
    tagline: 'The Heart of Modern Dubai',
    image: '/images/hero/img227.jpg',
    heroImage: '/images/hero/img201.jpg',
    description: 'Downtown Dubai is the world\'s most iconic urban address — home to the Burj Khalifa, Dubai Mall, and the Dubai Fountain. This 2km² district defines Dubai\'s global image and commands the city\'s highest property values. Residents enjoy unmatched access to luxury retail, fine dining, cultural institutions, and world-class entertainment, all within a meticulously planned, walkable neighbourhood.\n\nProperty values have appreciated 35% since 2023, driven by chronic undersupply of Burj Khalifa-view units and sustained international demand from European, CIS, and Indian buyers. Downtown Dubai remains the single most liquid real estate market in the UAE, with units regularly transacting within days of listing.',
    highlights: [
      'Burj Khalifa — the world\'s tallest building',
      'Dubai Mall — world\'s largest by total area',
      'AED 2,800–3,500/sqft average apartment prices',
      '5-min walk to Business Bay Canal',
    ],
    avgPricePerSqft: 'AED 3,100',
    rentalYield: '5.8%',
    propertyTypes: ['Apartments', 'Penthouses', 'Hotel-Serviced Residences'],
    nearbyAreas: ['Business Bay', 'DIFC', 'Dubai Design District'],
    lat: 25.1972,
    lng: 55.2744,
    mapZoom: 15,
  },
  {
    slug: 'dubai-marina',
    name: 'Dubai Marina',
    emirate: 'Dubai',
    tagline: 'Waterfront Living at Its Finest',
    image: '/images/hero/img302.jpg',
    heroImage: '/images/hero/img306.jpg',
    description: 'Dubai Marina is the UAE\'s premier waterfront community — a vibrant district of 200+ towers lining a 3.5km man-made canal marina. With over 56,000 residents from 100+ nationalities, it is one of Dubai\'s most cosmopolitan and energetic neighbourhoods. The Marina Walk promenade, JBR Beach, and Dubai Marina Mall form the lifestyle backbone of the community.\n\nThe area attracts a strong mix of young professionals, expat families, and international investors. Proximity to Media City, Internet City, and JLT makes it the first choice for tech and media sector residents. Short-term rental occupancy rates consistently exceed 90%, making it a top-tier Airbnb and holiday rental market.',
    highlights: [
      '3.5km marina promenade — one of the world\'s largest',
      'JBR Beach — Dubai\'s most popular public beach',
      '2 metro stations (Red Line)',
      'Best-in-class short-term rental market',
    ],
    avgPricePerSqft: 'AED 1,850',
    rentalYield: '6.2%',
    propertyTypes: ['Apartments', 'Penthouses', 'Duplexes'],
    nearbyAreas: ['JBR', 'JLT', 'Palm Jumeirah'],
    lat: 25.0805,
    lng: 55.1403,
    mapZoom: 14,
  },
  {
    slug: 'business-bay',
    name: 'Business Bay',
    emirate: 'Dubai',
    tagline: 'Dubai\'s Premier Mixed-Use Address',
    image: '/images/hero/img306.jpg',
    heroImage: '/images/properties/Binghatti-Hills-at-Dubai-HIlls.jpeg',
    description: 'Business Bay has evolved from a corporate district into one of Dubai\'s most dynamic and desirable mixed-use neighbourhoods. Straddling the Dubai Canal, it offers direct views of the Burj Khalifa to the north and the expanding creek corridor to the south. The canal promenade, lined with restaurants and luxury hotels, has become one of the city\'s most-visited social destinations.\n\nWith the highest off-plan transaction volumes in Dubai, Business Bay is the city\'s most active investment market. World-class developers including Binghatti, Damac, and Emaar have delivered landmark projects here, and the pipeline for 2026–2028 is the strongest in the city\'s history. Gross rental yields of 6.5–8.2% position it among Dubai\'s top-performing areas for passive income.',
    highlights: [
      'Canal promenade with waterfront dining',
      'Burj Khalifa visible from most towers',
      'Business Bay Metro — Red Line',
      'Highest off-plan volume in Dubai (Q1 2026)',
    ],
    avgPricePerSqft: 'AED 1,750',
    rentalYield: '7.4%',
    propertyTypes: ['Apartments', 'Penthouses', 'Commercial Units', 'Hotel Residences'],
    nearbyAreas: ['Downtown Dubai', 'DIFC', 'Meydan'],
    lat: 25.1866,
    lng: 55.2650,
    mapZoom: 14,
  },
  {
    slug: 'palm-jumeirah',
    name: 'Palm Jumeirah',
    emirate: 'Dubai',
    tagline: 'The Eighth Wonder of the World',
    image: '/images/hero/img333.jpg',
    heroImage: '/images/hero/img328.jpg',
    description: 'Palm Jumeirah is Dubai\'s most iconic address — an 8km man-made palm island that redefined what was architecturally possible. Home to ultra-luxury villas, signature branded residences, and internationally acclaimed hotels including Atlantis, FIVE Palm, and One&Only, it represents the pinnacle of luxury real estate in the UAE.\n\nThe Palm commands the highest price-per-sqft of any residential area in Dubai for standalone villas, with Signature Villas regularly trading above AED 30–80M. Frond villas offer private beach access, private pools, and lush garden settings, while the crescent tier delivers hotel-branded apartment living with panoramic sea views.',
    highlights: [
      'Private beach access on frond villas',
      'Home to Atlantis, FIVE Palm, One&Only',
      'World\'s longest monorail connects to mainland',
      'Average villa prices: AED 4,000–6,500/sqft',
    ],
    avgPricePerSqft: 'AED 4,800',
    rentalYield: '4.9%',
    propertyTypes: ['Villas', 'Townhouses', 'Apartments', 'Branded Residences'],
    nearbyAreas: ['Dubai Marina', 'JBR', 'Emirates Hills'],
    lat: 25.1124,
    lng: 55.1390,
    mapZoom: 13,
  },
  {
    slug: 'dubai-hills-estate',
    name: 'Dubai Hills Estate',
    emirate: 'Dubai',
    tagline: 'Dubai\'s Premier Family Community',
    image: '/images/hero/img508.jpg',
    heroImage: '/images/hero/img512.jpg',
    description: 'Dubai Hills Estate is Emaar\'s flagship master-planned community — 11 million sqm of thoughtfully designed residential, recreational, and retail space set around an 18-hole championship golf course. It is consistently ranked as Dubai\'s most desired family community and has become the benchmark against which all new master-plans are measured.\n\nThe community offers a full spectrum of property types, from affordable 1BR apartments to 8BR landmark mansions. Dubai Hills Mall, The School of Research Science, and GEMS International School anchor the community\'s retail and education offering. The 1.5km Dubai Hills Park is the largest community park in the UAE.',
    highlights: [
      '18-hole championship golf course',
      'Dubai Hills Mall — 650+ outlets',
      '45km of cycling and running tracks',
      'Top-rated schools within walking distance',
    ],
    avgPricePerSqft: 'AED 1,350',
    rentalYield: '5.8%',
    propertyTypes: ['Villas', 'Townhouses', 'Apartments', 'Mansions'],
    nearbyAreas: ['Al Barsha', 'Umm Suqeim', 'Meydan'],
    lat: 25.1209,
    lng: 55.2351,
    mapZoom: 14,
  },
  {
    slug: 'jumeirah-village-circle',
    name: 'Jumeirah Village Circle',
    emirate: 'Dubai',
    tagline: 'Dubai\'s Best-Value Investment Community',
    image: '/images/hero/img619.jpg',
    heroImage: '/images/hero/img619.jpg',
    description: 'Jumeirah Village Circle (JVC) has become synonymous with Dubai\'s best investment yields. Strategically located at the intersection of Al Khail Road and Mohammed Bin Zayed Road, JVC offers excellent connectivity to the city\'s key employment hubs while delivering the highest gross rental yields of any major Dubai community.\n\nWith over 40,000 units across 2,400 buildings and villas, JVC is a mature, self-contained community with parks, retail, cafes, and schools all within walking distance. Its competitive entry prices (AED 600–900/sqft) and strong rental demand from mid-market professionals make it the first choice for yield-focused investors.',
    highlights: [
      'Highest average rental yield in Dubai: 7.5–9.5%',
      'Entry prices from AED 600/sqft',
      'Strong infrastructure: parks, schools, retail',
      '25-minute drive to Dubai Marina',
    ],
    avgPricePerSqft: 'AED 750',
    rentalYield: '8.4%',
    propertyTypes: ['Apartments', 'Studios', 'Townhouses', 'Villas'],
    nearbyAreas: ['JVT', 'Dubai Hills', 'Motor City'],
    lat: 25.0592,
    lng: 55.2073,
    mapZoom: 14,
  },
  {
    slug: 'jumeirah-village-triangle',
    name: 'Jumeirah Village Triangle',
    emirate: 'Dubai',
    tagline: 'Serene Community Living, Strong Returns',
    image: '/images/hero/img692.jpg',
    heroImage: '/images/hero/img692.jpg',
    description: 'Jumeirah Village Triangle (JVT) is one of Dubai\'s most peaceful residential communities — a low-rise neighbourhood of villas, townhouses, and mid-rise apartments set among lush landscaped streets and community parks. Developed by Nakheel, JVT attracts families seeking a quieter pace of life without sacrificing urban connectivity.\n\nInvestment performance has been strong, with villas appreciating 22% in 2025 as supply in the sub-AED 5M villa segment remains constrained. Rental yields for apartments remain competitive at 6.5–8%, while villa rental demand from families relocating from JBR and Marina continues to grow.',
    highlights: [
      'Low-density, family-friendly community',
      'Villa prices: AED 2.8M–8M',
      'Parks, cycling tracks, community pools',
      '20-min drive to Dubai Mall',
    ],
    avgPricePerSqft: 'AED 820',
    rentalYield: '7.2%',
    propertyTypes: ['Villas', 'Townhouses', 'Apartments'],
    nearbyAreas: ['JVC', 'Dubai Hills', 'Sports City'],
    lat: 25.0493,
    lng: 55.1887,
    mapZoom: 14,
  },
  {
    slug: 'dubai-science-park',
    name: 'Dubai Science Park',
    emirate: 'Dubai',
    tagline: 'Where Innovation Meets Luxury Living',
    image: '/images/hero/img697.jpg',
    heroImage: '/images/properties/Binghatti-Hillside-at-Dubai-Science-Park.webp',
    description: 'Dubai Science Park is a purpose-built free zone and residential community anchored by one of the UAE\'s fastest-growing life sciences and technology clusters. The area has seen remarkable residential development activity, with Binghatti\'s Hillside development establishing a new benchmark for luxury apartments in this emerging corridor.\n\nResidenital properties in and around Dubai Science Park offer excellent value compared to mature communities, with strong capital appreciation potential driven by the expanding free zone employment base. Its central location — equidistant from Dubai Hills, JVC, and Al Barsha — makes it highly accessible to major employment hubs.',
    highlights: [
      'Home to Binghatti Hillside — landmark development',
      'Free zone hub with 400+ companies',
      'AED 900–1,200/sqft entry prices',
      'Strong capital appreciation potential',
    ],
    avgPricePerSqft: 'AED 1,050',
    rentalYield: '7.8%',
    propertyTypes: ['Apartments', 'Hotel Residences'],
    nearbyAreas: ['Dubai Hills', 'JVC', 'Al Barsha'],
    lat: 25.1004,
    lng: 55.2148,
    mapZoom: 14,
  },
  {
    slug: 'palm-jebel-ali',
    name: 'Palm Jebel Ali',
    emirate: 'Dubai',
    tagline: 'Dubai\'s Greatest Investment Opportunity',
    image: '/images/properties/616795878.jpg',
    heroImage: '/images/hero/img708.jpg',
    description: 'Palm Jebel Ali is Dubai\'s most transformative mega-development — a second palm island twice the size of Palm Jumeirah, developed by Nakheel under the visionary Dubia 2040 Urban Master Plan. With Phase 1 frond villas completely sold out at launch and Phase 2 commanding AED 4,500–6,500/sqft, early investors have already accumulated 40–60% paper gains.\n\nPalm Jebel Ali will ultimately house 35 hotels, 80 resort-style beach clubs, and communities for 250,000 residents. Infrastructure works are progressing rapidly, with road and utilities networks already visible. This is the defining generational investment opportunity in Dubai real estate.',
    highlights: [
      'Twice the size of Palm Jumeirah',
      '80 beachfront resort communities planned',
      'Phase 1 sold out at launch — 60% appreciation recorded',
      'Completion targeted: 2027–2029',
    ],
    avgPricePerSqft: 'AED 5,200',
    rentalYield: '4.5% (projected)',
    propertyTypes: ['Villas', 'Frond Villas', 'Beach Houses'],
    nearbyAreas: ['Dubai Marina', 'Jebel Ali', 'Dubai South'],
    lat: 24.9942,
    lng: 55.0226,
    mapZoom: 13,
  },
  {
    slug: 'difc',
    name: 'DIFC',
    emirate: 'Dubai',
    tagline: 'The Financial Capital of the Middle East',
    image: '/images/hero/img737.jpg',
    heroImage: '/images/hero/img737.jpg',
    description: 'The Dubai International Financial Centre (DIFC) is the Middle East\'s most prestigious financial hub — home to 6,500+ registered companies including Goldman Sachs, HSBC, JPMorgan, and every major global law firm and accounting practice. As a financial free zone with its own legal system (DIFC Courts, based on English common law), it is the first choice for international businesses operating in the MEASA region.\n\nResidential properties within DIFC command significant premiums reflecting its exclusivity and the ultra-high-net-worth professional demographic. Gate Avenue, with its curated luxury retail and dining, and the proximity to Downtown Dubai, make DIFC one of the most sought-after addresses for C-suite professionals and international executives.',
    highlights: [
      'Home to 6,500+ global financial firms',
      'DIFC Courts — English common law jurisdiction',
      'Gate Avenue — curated luxury retail & dining',
      '3 min walk to Downtown Dubai',
    ],
    avgPricePerSqft: 'AED 3,400',
    rentalYield: '5.5%',
    propertyTypes: ['Apartments', 'Penthouses', 'Serviced Residences'],
    nearbyAreas: ['Downtown Dubai', 'Business Bay', 'Za\'abeel'],
    lat: 25.2048,
    lng: 55.2827,
    mapZoom: 15,
  },
  {
    slug: 'reem-island',
    name: 'Reem Island',
    emirate: 'Abu Dhabi',
    tagline: 'Abu Dhabi\'s Most Coveted Address',
    image: '/images/hero/img767.jpg',
    heroImage: '/images/hero/img767.jpg',
    description: 'Reem Island is Abu Dhabi\'s most prominent waterfront community — a 6.5 million sqm island located 600m from the Abu Dhabi mainland. Home to the Macins Luxe Abu Dhabi office, Reem Island offers a remarkable quality of life with its natural reserves, world-class parks, premium schools, and a growing retail and dining scene anchored by Shams Boutik Mall.\n\nProperty values on Reem Island have benefited from continued government investment in Abu Dhabi\'s economy and the expansion of the Louvre Abu Dhabi cultural district nearby. Apartments deliver strong rental yields of 7–9%, driven by demand from government employees, Mubadala professionals, and international executives.',
    highlights: [
      'Natural reserve and protected mangroves',
      'Shams Boutik Mall and Cleveland Clinic Abu Dhabi',
      'Direct connection to Abu Dhabi mainland via bridges',
      'Macins Luxe Abu Dhabi office located here',
    ],
    avgPricePerSqft: 'AED 1,100',
    rentalYield: '7.8%',
    propertyTypes: ['Apartments', 'Townhouses', 'Villas'],
    nearbyAreas: ['Al Raha Beach', 'Saadiyat Island', 'Abu Dhabi Corniche'],
    lat: 24.5027,
    lng: 54.4069,
    mapZoom: 14,
  },
  {
    slug: 'yas-island',
    name: 'Yas Island',
    emirate: 'Abu Dhabi',
    tagline: 'Luxury Living Meets World-Class Entertainment',
    image: '/images/hero/img803.jpg',
    heroImage: '/images/hero/img803.jpg',
    description: 'Yas Island is Abu Dhabi\'s premier entertainment and residential destination — home to Yas Marina Circuit (F1 Abu Dhabi Grand Prix), Ferrari World, Yas Waterworld, Warner Bros. World, and the acclaimed Yas Marina. Developed by Aldar Properties, it is the fastest-growing residential market in Abu Dhabi.\n\nThe island\'s exceptional lifestyle infrastructure, including Yas Mall, W Yas Island, and the upcoming Yas Bay Waterfront development, makes it particularly attractive to families and hospitality-sector professionals. Proximity to Abu Dhabi International Airport (15 minutes) is a major draw for frequent international travellers and expat executives.',
    highlights: [
      'Yas Marina Circuit — F1 Abu Dhabi Grand Prix',
      'Ferrari World, Yas Waterworld, Warner Bros. World',
      '15 min from Abu Dhabi International Airport',
      'Yas Bay Waterfront — major new waterfront hub',
    ],
    avgPricePerSqft: 'AED 950',
    rentalYield: '7.5%',
    propertyTypes: ['Apartments', 'Villas', 'Townhouses'],
    nearbyAreas: ['Al Raha Beach', 'Saadiyat Island', 'Khalifa City'],
    lat: 24.4672,
    lng: 54.6031,
    mapZoom: 13,
  },
];
